### PR TITLE
feat:Improve Simplified Chinese translation

### PR DESCRIPTION
**Pull request by flower-elf**
Improve Simplified Chinese translation.
fix some error and adjusted translation of common strings
Due to time constraints, some translations were not completed.
Thanks

co-name:flower_elf
Github:flower_elf(flower-elf)
twitter:@u_flower_elf

### CODE REVIEW

**Comment by Raphiiko** [comment]
Hey @flower-elf, thanks for the contribution! I'd love to merge this, but I sadly cannot merge incomplete translations (read: translation values containing `{{PLACEHOLDER}}`). This is because the translation system relies on keys being completely missing in order to properly fall back to the English translations, and these keys being present prevents that fallback mechanism from working. 

The empty `{{PLACEHOLDER}}` keys either have to be removed, or I can keep this PR open until you can find the time to complete it. I would very much suggest the former, as the translations getting changed over time might make this more difficult to merge eventually.

**Comment by flower-elf** [comment]
I'm aware of the issue and will reopen the PR when the process is complete

**Comment by flower-elf** [comment]
Hello @Raphiiko  
I've finished all the translations, which should be ready to be reviewed and merged by now

This tool is great, thanks for developing it!

**Comment by Raphiiko** [comment]
Thank you! I've added credit for your changes in [this commit](https://github.com/Raphiiko/OyasumiVR/pull/45/commits/882207710527e8a06569c111afe8e91a5eeb5bdc). If you'd like me to change your name or link to something else, feel free to let me know!

**Pull request merged**
